"""Risk layer (SPEC v2 §7): CRN bump-and-reprice engine, delta regimes, vega variants, theta,
ladders, profiles, parameter sensitivities, product-specific risks, precision estimators,
attribution and the RiskReport."""

from __future__ import annotations

from volsto.risk.attribution import Explain, Step, explain
from volsto.risk.digital_risk import (
    BARRIER_SHIFT_SCOPES,
    CERTAIN_AUTOCALL,
    SKEW_BUMP,
    SmoothedAutocall,
    autocall_spot_profiles,
    callable_dates,
    default_profile_shifts,
    expected_life_sensitivity,
    ki_barrier_profile,
    ki_put_barrier_risk,
    lr_cross_check,
    residual_note,
    shifted_levels,
    structure_vega_skew,
)
from volsto.risk.engine import (
    BSBuilder,
    LSVBuilder,
    LVBuilder,
    ModelBuilder,
    RiskEngine,
    RiskState,
    Sensitivity,
    surface_of,
)
from volsto.risk.estimators import (
    ConditionalGreeks,
    ControlledSensitivity,
    compare,
    conditional_greeks,
    cv_difference,
    lr_delta,
    lr_vega,
)
from volsto.risk.greeks import (
    REGIMES,
    ThetaReport,
    cross_greeks,
    delta_gamma,
    delta_table,
    theta,
    vega,
)
from volsto.risk.ladders import (
    PILLARS,
    Ladder,
    VegaTermStructure,
    check_pillars_calendar,
    curvature_T,
    default_buckets,
    fwd_var_convexity,
    fwd_var_ladder,
    skew_T,
    varswap_bucket_sensitivity,
    vega_T,
)
from volsto.risk.product_risk import (
    barrier_profile,
    barrier_sensitivity,
    fixing_risk,
    ko_probability_delta,
    realised_variance_exposure,
)
from volsto.risk.profiles import (
    CliquetGammaProfile,
    bachelier_cliquet_value,
    bs_cliquet_value_mc,
    cliquet_gamma_profile,
    spot_profile,
)
from volsto.risk.report import SECTIONS, RiskReport, risk_report, smart_gap_table
from volsto.risk.volsto_sens import PARAMS, parameter_sensitivities, parameter_sensitivity

__all__ = [
    "BARRIER_SHIFT_SCOPES",
    "CERTAIN_AUTOCALL",
    "PARAMS",
    "PILLARS",
    "REGIMES",
    "SECTIONS",
    "SKEW_BUMP",
    "BSBuilder",
    "CliquetGammaProfile",
    "ConditionalGreeks",
    "ControlledSensitivity",
    "Explain",
    "LSVBuilder",
    "LVBuilder",
    "Ladder",
    "ModelBuilder",
    "RiskEngine",
    "RiskReport",
    "RiskState",
    "Sensitivity",
    "SmoothedAutocall",
    "Step",
    "ThetaReport",
    "VegaTermStructure",
    "[",
    "autocall_spot_profiles",
    "bachelier_cliquet_value",
    "barrier_profile",
    "barrier_sensitivity",
    "bs_cliquet_value_mc",
    "callable_dates",
    "check_pillars_calendar",
    "cliquet_gamma_profile",
    "compare",
    "conditional_greeks",
    "cross_greeks",
    "curvature_T",
    "cv_difference",
    "default_buckets",
    "default_profile_shifts",
    "delta_gamma",
    "delta_table",
    "expected_life_sensitivity",
    "explain",
    "fixing_risk",
    "fwd_var_convexity",
    "fwd_var_ladder",
    "ki_barrier_profile",
    "ki_put_barrier_risk",
    "ko_probability_delta",
    "lr_cross_check",
    "lr_delta",
    "lr_vega",
    "parameter_sensitivities",
    "parameter_sensitivity",
    "realised_variance_exposure",
    "residual_note",
    "risk_report",
    "shifted_levels",
    "skew_T",
    "smart_gap_table",
    "spot_profile",
    "structure_vega_skew",
    "surface_of",
    "theta",
    "varswap_bucket_sensitivity",
    "vega",
    "vega_T",
]
