"""M10 Part 3 (G1): the repaired eSSVI surface survives the config, cache and risk paths (SPEC
§13.2).

The invariant, enforced in two places and walked here (CONTRIBUTING, third-occurrence rule):
**a surface is built from a config only by** :func:`volsto.market.surface.surface_from_config`
**and a surface config is read from a file only by**
:func:`volsto.market.loaders.load_surface_config`, so an eSSVI snapshot (per-pillar ``ρ_T``,
``essvi`` section) reaches the leverage calibration and every risk bump as the eSSVI surface,
never as its mean-``ρ`` SSVI.  The hard constraint: a config without ``rhos`` maps — and hashes —
byte for byte as before the field existed (:func:`volsto.config.omitted_when_none`), checked on
the keys of the committed specs and grids recorded before the change and, read-only, against the
repository's leverage-cache manifest.

No calibration, no Monte Carlo.
"""

from __future__ import annotations

import ast
import dataclasses
import hashlib
import json
from collections.abc import Callable
from pathlib import Path

import numpy as np
import pandas as pd
import pytest
import yaml

from volsto.calibration.cache import build_market, spec_key
from volsto.config import (
    BergomiParams,
    CalibrationSpec,
    ConfigError,
    SimConfig,
    SSVIConfig,
    SurfacePerturbation,
    dump_yaml,
    from_mapping,
    load_yaml,
    to_mapping,
)
from volsto.market import ESSVISurface, ForwardCurve, LocalVolSurface, SSVISurface
from volsto.market.loaders import load_ssvi_surface, load_surface_config, snapshot_spec
from volsto.market.surface import PerturbedSurface, surface_from_config
from volsto.market.varswap import varswap_strike
from volsto.risk.engine import BSBuilder, RiskEngine, RiskState, surface_of
from volsto.studies.m4 import HEADLINE_OMEGAS, one_factor_variants
from volsto.viewers.grid import enumerate_points, load_grid, lv_key, reference_spec, surface_spec

ROOT = Path(__file__).resolve().parents[1]
SNAPSHOTS = ROOT / "configs" / "surfaces" / "snapshots"
ESSVI_SNAPSHOT = SNAPSHOTS / "spx_2022-12-02.yaml"
"""A committed eSSVI snapshot (``essvi`` section; M3b fit, loads under the constructor check)."""
SSVI_SNAPSHOT = SNAPSHOTS / "hdn_2022H2_ssvi" / "spx_2022-12-30.yaml"
GATE_SNAPSHOTS = ROOT / "outputs" / "essvi_gate" / "snapshots"
"""The repaired 2022 H2 history of M10 Part 0 (git-ignored; regenerated by the gate script)."""
MANIFEST = ROOT / "cache" / "manifest.parquet"
STUDIES = ROOT / "configs" / "studies"
GRIDS = ROOT / "configs" / "grids"

# --------------------------------------------------------------------------------------------
# keys recorded on 2026-09-16 with the code of commit 0ca0897 (before SSVIConfig.rhos existed)
# --------------------------------------------------------------------------------------------

RECORDED_SPEC_KEYS: dict[str, str] = {
    "lsv_reference_1f.yaml": "831dd92b8b20dde68e314dae51b30c0df4d190f63479d623b0940e2113a6ae33",
    "lsv_reference_2f.yaml": "6a007884b6de9bd0b7dad2540e77ad5f647268783d76ea2586a2a426609d937c",
    "lsv_reference_2f_nu087.yaml": (
        "b35b49ac47ffd4d2b0617fa5604b93e328c6496af7d0d94543b16284c3114697"
    ),
    "m7_p1_marking/reference_ssr1.5_eps0.05.yaml": (
        "5bb70579399d9974bd2bf30b4f3a9fbf8a3de122156063938128c70627af405d"
    ),
    "m7_p1_marking/reference_ssr1_eps0.1.yaml": (
        "2f14cad8e868274de720d632fdbf7794111a388347c365a1d7994b7e4e68cdb9"
    ),
    "m7_p1_marking/spx_ssr1.5_eps0.05.yaml": (
        "6bf536715bce6a86715c4e138399b2e6340312eade6f9d5aad3cde1e505ec52a"
    ),
    "m7_p1_marking/spx_ssr1.75_eps0.2.yaml": (
        "1b76d7538370e4e9454b5f2d5f72c25d17e63cf5d89ee0b0036f3dff95dad20e"
    ),
    "m7_p1_marking/spx_ssr1_eps0.1.yaml": (
        "6f6302bac31c7683dcc0a6fdaac59085f37aa5650ad0256afe4994564232b615"
    ),
}
"""``spec_key`` of the committed calibration specs (a whole-file spec, or the ``spec`` section of
an M7 marking record)."""
RECORDED_M6_HEADLINE_KEYS: dict[str, str] = {
    "1F ω=1": "41d7b5efa43f53538155386d47015a57a30f2c1d2578a02b258e01c1c5fd1ef1",
    "1F ω=2": "82c45cffc3ef940ac139ccc7d45f2935c9842a642ca38cb298b8e2b3017fe21a",
    "1F ω=3": "d93d4d79b7d25b4329a8a0ad9718d2da7a3a084fff52852b1f4c5320543fb137",
    "2F Table 8.2": "29719be67072c7d766af145cba91f2261bc9c4be4499f1a4787e2d2e0bfc76fa",
}
"""The M6 headline calibrations (``lsv_reference_1f`` / ``_2f`` at 8·10⁵ particles)."""
RECORDED_M8B_SPX_KEY = "b81b684f1bf1d578d9f522cd561e225f4f52551a872ee3ad37bf3dd6a2a1c0b1"
"""``volsto.studies.m8b.spx_base_spec(800_000)`` (the plain-SSVI 2022-12-30 snapshot)."""
PLACEHOLDER_LV = "lv:9a912c0ffbc703a849ce2922eaa21badbb02c031d84bdba019a77dc22f37a501"
RECORDED_GRID_KEYS: dict[str, dict[str, str | None]] = {
    "toy": {
        PLACEHOLDER_LV: None,
        "0d387758308786573996fd175a03332abbcce5aefd3abce8fdcfa0f197b8bdd9": (
            "0d387758308786573996fd175a03332abbcce5aefd3abce8fdcfa0f197b8bdd9"
        ),
        "e2974071768a24ff6680e625bdbbcc62332985e64c6f1af93e0cacabaaada62d": (
            "e2974071768a24ff6680e625bdbbcc62332985e64c6f1af93e0cacabaaada62d"
        ),
        "01b91f71d2ba5134b70427fa604db411447744bec301fcfa0563309d6e0ece85": (
            "01b91f71d2ba5134b70427fa604db411447744bec301fcfa0563309d6e0ece85"
        ),
    },
    "placeholder_cached": {
        PLACEHOLDER_LV: None,
        **{k: k for k in RECORDED_M6_HEADLINE_KEYS.values()},
    },
}
"""Point id → leverage-cache key of the two small grids (the toy grid's keys are those the test
suite's fixture calibrates)."""
RECORDED_DEFAULT_GRID_DIGEST = (
    105,
    "95e0a5fa88c9a51eaa498513385c28a5c543068e3afb2a78f30db87351eea7ce",
)
"""``(count, SHA-256)`` of ``"id=key"`` lines of the default grid's points on its plain-SSVI
surfaces (``placeholder``, ``spx_2022-12-30``), sorted by id."""
RECORDED_LV_IDS: dict[str, str] = {
    "placeholder": PLACEHOLDER_LV,
    "spx_2022-12-30": "lv:738c9cc86ce4838a4d796445e7581b92a4ec443952d60e1538870e96e7996aed",
}
FLATTENED_LV_IDS: dict[str, str] = {
    "spx_2022-09-15": "lv:c0e02417fd38ad176bdfa2695be6fdf35aae922400e938ab5ec77e3cfb41b74d",
    "spx_2022-12-02": "lv:abe1f0eda308ae5211c59c7fa6615303ab2115cb851d8b3ab4f61a73bb7a105d",
}
"""The default grid's LV ids of its two eSSVI snapshots BEFORE the change, when the grid read
them flattened to the mean rho: they change deliberately (the LV point of an eSSVI surface is
now the eSSVI's Dupire); no store or cache held them (checked below when the store exists)."""
IN_MANIFEST_AT_RECORDING: tuple[str, ...] = (
    RECORDED_SPEC_KEYS["m7_p1_marking/reference_ssr1.5_eps0.05.yaml"],
    RECORDED_SPEC_KEYS["m7_p1_marking/reference_ssr1_eps0.1.yaml"],
    RECORDED_SPEC_KEYS["m7_p1_marking/spx_ssr1.5_eps0.05.yaml"],
    RECORDED_SPEC_KEYS["m7_p1_marking/spx_ssr1.75_eps0.2.yaml"],
    RECORDED_SPEC_KEYS["m7_p1_marking/spx_ssr1_eps0.1.yaml"],
    *RECORDED_M6_HEADLINE_KEYS.values(),
)
"""Recorded keys that address entries of the repository cache (291 rows on 2026-09-16)."""


def _committed_spec(rel: str) -> CalibrationSpec:
    path = STUDIES / rel
    raw = yaml.safe_load(path.read_text(encoding="utf-8"))
    if "spec" in raw:
        return from_mapping(CalibrationSpec, raw["spec"], path=str(path))
    return load_yaml(path, CalibrationSpec)


def _with_particles(spec: CalibrationSpec, n: int) -> CalibrationSpec:
    return dataclasses.replace(spec, particle=dataclasses.replace(spec.particle, n_particles=n))


def _m6_headline_keys() -> dict[str, str]:
    one = _with_particles(load_yaml(STUDIES / "lsv_reference_1f.yaml", CalibrationSpec), 800_000)
    two = _with_particles(load_yaml(STUDIES / "lsv_reference_2f.yaml", CalibrationSpec), 800_000)
    keys = {name: spec_key(s) for name, s in one_factor_variants(one, HEADLINE_OMEGAS).items()}
    keys["2F Table 8.2"] = spec_key(two)
    return keys


def _default_grid_digest() -> tuple[int, str]:
    grid = load_grid(GRIDS / "default.yaml")
    points = [p for p in enumerate_points(grid) if p.surface in ("placeholder", "spx_2022-12-30")]
    lines = sorted(f"{p.id}={p.cache_key}" for p in points)
    return len(lines), hashlib.sha256("\n".join(lines).encode()).hexdigest()


# --------------------------------------------------------------------------------------------
# the config field
# --------------------------------------------------------------------------------------------


def test_rhos_field_validation_and_mapping() -> None:
    plain = SSVIConfig((0.5, 1.0), (0.2, 0.21), -0.7, 1.0, 0.5)
    assert plain.rhos is None and "rhos" not in to_mapping(plain)
    e = SSVIConfig((0.5, 1.0), (0.2, 0.21), -0.7, 1.0, 0.5, rhos=[-0.6, -0.8])  # type: ignore[arg-type]
    assert e.rhos == (-0.6, -0.8) and isinstance(e.rhos, tuple)
    assert to_mapping(e)["rhos"] == [-0.6, -0.8]
    assert from_mapping(SSVIConfig, to_mapping(e)) == e
    assert from_mapping(SSVIConfig, to_mapping(plain)) == plain
    hash(e)  # a frozen config stays hashable
    for bad in ((-0.6,), (-0.6, -1.0), (-0.6, float("nan")), (0.2, 1.5)):
        with pytest.raises(ValueError, match="rhos"):
            SSVIConfig((0.5, 1.0), (0.2, 0.21), -0.7, 1.0, 0.5, rhos=bad)
    with pytest.raises(ConfigError):
        from_mapping(
            SSVIConfig,
            {
                "atm_maturities": [1.0],
                "atm_vols": [0.2],
                "rho": 0.0,
                "eta": 1.0,
                "gamma": 0.5,
                "rhos": [1.2],
            },
        )


def test_keys_of_committed_specs_unchanged() -> None:
    """The hard constraint: every committed spec and grid point without ``rhos`` hashes to the
    key it had before the field existed (recorded literally above)."""
    for rel, key in RECORDED_SPEC_KEYS.items():
        spec = _committed_spec(rel)
        assert spec.surface.rhos is None, rel
        assert spec_key(spec) == key, rel
        assert "rhos" not in json.dumps(spec.key_payload()), rel
    assert _m6_headline_keys() == RECORDED_M6_HEADLINE_KEYS
    from volsto.studies.m8b import spx_base_spec

    assert spec_key(spx_base_spec(800_000)) == RECORDED_M8B_SPX_KEY
    for name, recorded in RECORDED_GRID_KEYS.items():
        grid = load_grid(GRIDS / f"{name}.yaml")
        assert {p.id: p.cache_key for p in enumerate_points(grid)} == recorded, name
        ref = reference_spec(grid)
        assert lv_key(surface_spec(grid, grid.surface("placeholder"), ref)) == PLACEHOLDER_LV
    assert _default_grid_digest() == RECORDED_DEFAULT_GRID_DIGEST
    grid = load_grid(GRIDS / "default.yaml")
    ref = reference_spec(grid)
    for name, recorded_id in RECORDED_LV_IDS.items():
        assert lv_key(surface_spec(grid, grid.surface(name), ref)) == recorded_id, name


def test_keys_against_the_repository_cache_manifest() -> None:
    """Read-only: the recorded keys that addressed cache entries still do, and every one of them
    is reproduced by the current code (the manifest only grows)."""
    if not MANIFEST.exists():
        pytest.skip(f"no leverage-cache manifest at {MANIFEST}")
    keys = set(pd.read_parquet(MANIFEST, columns=["key"])["key"])
    current = {spec_key(_committed_spec(rel)) for rel in RECORDED_SPEC_KEYS}
    current |= set(_m6_headline_keys().values())
    for key in IN_MANIFEST_AT_RECORDING:
        assert key in keys, key
        assert key in current, key
    for name, old in FLATTENED_LV_IDS.items():
        # the deliberately changed ids addressed nothing
        assert old not in keys, name
    store = ROOT / "outputs" / "store" / "results" / "points"
    if store.is_dir():
        stored = {p.name for p in store.iterdir()}
        for old in FLATTENED_LV_IDS.values():
            assert old.replace(":", "__") not in stored


# --------------------------------------------------------------------------------------------
# the snapshot → spec → surface path
# --------------------------------------------------------------------------------------------


def test_essvi_snapshot_config_carries_rhos(tmp_path: Path) -> None:
    raw = yaml.safe_load(ESSVI_SNAPSHOT.read_text(encoding="utf-8"))
    cfg = load_surface_config(ESSVI_SNAPSHOT)
    assert cfg.rhos == tuple(raw["essvi"]["rhos"])
    assert cfg.rho == raw["ssvi"]["rho"]  # the scalar stays (informational)
    assert load_surface_config(SSVI_SNAPSHOT).rhos is None
    # the grid's specs of the eSSVI surfaces carry the pillar rhos, and their LV ids moved
    grid = load_grid(GRIDS / "default.yaml")
    ref = reference_spec(grid)
    for name, old in FLATTENED_LV_IDS.items():
        spec = surface_spec(grid, grid.surface(name), ref)
        assert spec.surface.rhos is not None and len(spec.surface.rhos) >= 5, name
        assert lv_key(spec) != old
        flat = dataclasses.replace(spec, surface=dataclasses.replace(spec.surface, rhos=None))
        assert lv_key(flat) == old  # the old id was the flattened surface's
    # snapshot_spec and a spec round trip keep them; the key sees them
    base = load_yaml(STUDIES / "lsv_reference_2f.yaml", CalibrationSpec)
    spec = snapshot_spec(base, ESSVI_SNAPSHOT)
    assert spec.surface == cfg and spec.model == base.model
    dump_yaml(spec, tmp_path / "spec.yaml")
    back = load_yaml(tmp_path / "spec.yaml", CalibrationSpec)
    assert back == spec and spec_key(back) == spec_key(spec)
    flat = dataclasses.replace(spec, surface=dataclasses.replace(cfg, rhos=None))
    assert spec_key(flat) != spec_key(spec)
    # strictness of the essvi section
    text = ESSVI_SNAPSHOT.read_text(encoding="utf-8")
    for body, match in (
        ({"rhos": raw["essvi"]["rhos"], "extra": 1}, "exactly"),
        ({"rhos": raw["essvi"]["rhos"][:-1]}, "one correlation per ATM pillar"),
    ):
        bad = dict(raw, essvi=body)
        p = tmp_path / "bad.yaml"
        p.write_text(yaml.safe_dump(bad), encoding="utf-8")
        with pytest.raises(ConfigError, match=match):
            load_surface_config(p)
    both = dict(raw, ssvi={**raw["ssvi"], "rhos": raw["essvi"]["rhos"]})
    p = tmp_path / "both.yaml"
    p.write_text(yaml.safe_dump(both), encoding="utf-8")
    with pytest.raises(ConfigError, match="both"):
        load_surface_config(p)
    assert text == ESSVI_SNAPSHOT.read_text(encoding="utf-8")


def test_factory_builds_the_essvi_on_every_path() -> None:
    """The loader, the cache's market, the risk engine and the ``from_config`` alias all return
    the eSSVI surface of an eSSVI config, identical to a direct construction; the pure-SV
    kernel's ξ₀ (the leverage calibration's input) is the eSSVI's, not the flattened one's."""
    cfg = load_surface_config(ESSVI_SNAPSHOT)
    base = load_yaml(STUDIES / "lsv_reference_2f.yaml", CalibrationSpec)
    spec = snapshot_spec(base, ESSVI_SNAPSHOT)
    fc = ForwardCurve.from_config(spec.market)
    t, v = np.asarray(cfg.atm_maturities), np.asarray(cfg.atm_vols)
    assert cfg.rhos is not None
    direct = ESSVISurface(
        t, v * v * t, cfg.rhos, cfg.eta, cfg.gamma, fc, fc.rate_curve, max_maturity=3.0
    )
    ks = np.linspace(-1.0, 1.0, 41)[None, :]
    ts = np.array([0.1, 0.5, 1.0, 1.7, 2.5, 3.0])[:, None]
    w0 = direct.total_variance(ks, ts)
    surfaces = {
        "factory": surface_from_config(cfg, fc, fc.rate_curve),
        "alias": SSVISurface.from_config(cfg, fc, fc.rate_curve),
        "loader": load_ssvi_surface(ESSVI_SNAPSHOT),
        "risk": surface_of(RiskState(spec)),
    }
    for name, s in surfaces.items():
        assert isinstance(s, ESSVISurface), name
        np.testing.assert_array_equal(s.total_variance(ks, ts), w0, err_msg=name)
    flat_cfg = dataclasses.replace(cfg, rhos=None)
    flat = surface_from_config(flat_cfg, fc, fc.rate_curve)
    assert type(flat) is SSVISurface
    assert np.max(np.abs(flat.total_variance(ks, ts) - w0)) > 1e-3  # the flattening mattered
    # the cache's market: eSSVI surface and its variance-swap strip in the kernel
    _, surface, kernel = build_market(spec)
    assert isinstance(surface, ESSVISurface)
    _, _, kernel_flat = build_market(dataclasses.replace(spec, surface=flat_cfg))
    grid_t = np.linspace(0.05, 3.0, 30)
    xi_e, xi_f = kernel.xi0.xi0(grid_t), kernel_flat.xi0.xi0(grid_t)
    assert np.max(np.abs(xi_e - xi_f)) > 1e-4
    k_e = float(varswap_strike(surface, 2.0))
    k_f = float(varswap_strike(flat, 2.0))
    print(
        f"2y variance-swap vol: eSSVI {np.sqrt(k_e) * 100:.3f}% vs mean-rho SSVI "
        f"{np.sqrt(k_f) * 100:.3f}%; max |xi0 difference| {np.max(np.abs(xi_e - xi_f)):.2e}"
    )
    assert abs(np.sqrt(k_e) - np.sqrt(k_f)) > 1e-4
    # the local-vol builder's Dupire runs on the eSSVI surface
    lv = LocalVolSurface.from_implied(surface, spec.local_vol)
    assert np.all(np.isfinite(lv.local_var)) and np.all(lv.local_var > 0)


def _repaired_gate_snapshot() -> Path | None:
    if not GATE_SNAPSHOTS.is_dir():
        return None
    for path in sorted(GATE_SNAPSHOTS.glob("spx_*.yaml")):
        raw = yaml.safe_load(path.read_text(encoding="utf-8"))
        if raw.get("provenance", {}).get("fit", {}).get("calendar_repaired") and "essvi" in raw:
            return path
    return None


def test_calendar_certificate_survives_the_config_path(tmp_path: Path) -> None:
    """SPEC §13.1's invariant — ``∂_T w ≥ margin`` proven on ``|k| ≤ 3`` — holds on the surface
    the leverage cache builds from the snapshot's spec: the importer's certificate is
    re-proven on the rebuilt surface with the importer's own lower bound.  A repaired day of the
    M10 Part 0 history when present; always a synthetic eSSVI written and read back."""
    base = load_yaml(STUDIES / "lsv_reference_2f.yaml", CalibrationSpec)
    gate = _repaired_gate_snapshot()
    if gate is not None:
        fit = yaml.safe_load(gate.read_text(encoding="utf-8"))["provenance"]["fit"]
        _, surface, _ = build_market(snapshot_spec(base, gate))
        assert isinstance(surface, ESSVISurface)
        cert = surface.calendar_certificate(
            k_abs=fit["calendar_k_abs"], floor=fit["calendar_floor"]
        )
        print(f"{gate.name}: {cert.status}, lower bound {cert.lower_bound:.6e} (importer "
              f"{fit['calendar_lower_bound']:.6e}), min {cert.min_value:.6e}")  # fmt: skip
        assert cert.certified
        assert cert.lower_bound == pytest.approx(fit["calendar_lower_bound"], rel=1e-9)
        assert cert.min_value == pytest.approx(fit["calendar_min_dw_dt"], rel=1e-9)
    # synthetic: a certified eSSVI, written as a snapshot and rebuilt from the config
    fc = ForwardCurve.flat(100.0, 0.02, 0.01)
    pil = np.array([1 / 12, 0.25, 0.5, 1.0, 2.0, 3.0])
    vols = np.array([0.24, 0.22, 0.21, 0.205, 0.205, 0.21])
    rhos = np.array([-0.45, -0.55, -0.62, -0.68, -0.70, -0.70])
    direct = ESSVISurface(pil, vols**2 * pil, rhos, 0.9, 0.45, fc, fc.rate_curve, max_maturity=3.0)
    cert0 = direct.calendar_certificate(k_abs=3.0, floor=1e-4)
    assert cert0.certified
    snap = {
        "market": {
            "spot": 100.0,
            "rate_curve": {"times": [1.0], "rates": [0.02]},
            "dividend_curve": {"times": [1.0], "rates": [0.01]},
        },
        "ssvi": {
            "atm_maturities": pil.tolist(),
            "atm_vols": vols.tolist(),
            "rho": float(rhos.mean()),
            "eta": 0.9,
            "gamma": 0.45,
            "max_maturity": 3.0,
        },
        "essvi": {"rhos": rhos.tolist()},
    }
    path = tmp_path / "synthetic.yaml"
    path.write_text(yaml.safe_dump(snap), encoding="utf-8")
    _, rebuilt, _ = build_market(snapshot_spec(base, path))
    assert isinstance(rebuilt, ESSVISurface)
    cert1 = rebuilt.calendar_certificate(k_abs=3.0, floor=1e-4)
    assert cert1.certified
    assert cert1.lower_bound == pytest.approx(cert0.lower_bound, rel=1e-9)


PERTURBATIONS: tuple[SurfacePerturbation, ...] = (
    SurfacePerturbation("parallel", {"size": 0.01}),
    SurfacePerturbation("tent", {"pillars": [0.25, 1.0, 2.0], "index": 1, "size": 0.01}),
    SurfacePerturbation("skew_tent", {"pillars": [0.25, 1.0, 2.0], "index": 1, "slope": 0.02}),
    SurfacePerturbation("curvature_tent", {"pillars": [0.25, 1.0, 2.0], "index": 1, "curv": 0.02}),
    SurfacePerturbation("rotation", {"size": 1.0, "t_min": 1 / 12}),
    SurfacePerturbation("shift_k", {"delta": 0.01}),
    SurfacePerturbation("atm_shift", {"delta": 0.01, "factor": 1.0, "t_min": 1 / 12}),
    SurfacePerturbation("total_variance", {"eps": 0.05, "t_lo": 0.5, "t_hi": 1.0}),
    SurfacePerturbation("roll", {"dt": 1 / 252}),
    SurfacePerturbation("table", {"ks": [-0.2, 0.2], "ts": [0.5, 2.0], "values": [0, 0.01, 0, 0]}),
    SurfacePerturbation(
        "composite",
        {
            "items": [
                {"kind": "parallel", "params": {"size": 0.005}},
                {"kind": "shift_k", "params": {"delta": -0.01}},
            ]
        },
    ),
)


def _constant(pert: SurfacePerturbation) -> Callable[[float], SurfacePerturbation]:
    """A bump maker returning ``pert`` whatever the size (the engine's halving is not needed)."""

    def make(_size: float) -> SurfacePerturbation:
        return pert

    return make


def _skew_tent(slope: float) -> SurfacePerturbation:
    return SurfacePerturbation("skew_tent", {"pillars": [0.25, 1.0], "index": 0, "slope": slope})


def test_risk_bumps_on_the_essvi_surface() -> None:
    """Every perturbation kind layers on the eSSVI base (the risk engine's bumps), passes the
    arbitrage checks or halves through the engine, and moves the vols as defined."""
    base_spec = load_yaml(STUDIES / "lsv_reference_2f.yaml", CalibrationSpec)
    spec = dataclasses.replace(
        snapshot_spec(base_spec, ESSVI_SNAPSHOT), model=BergomiParams.one_factor(1.0, 1.0, -0.7)
    )
    state = RiskState(spec)
    base = surface_of(state)
    assert isinstance(base, ESSVISurface)
    engine = RiskEngine(BSBuilder(state), SimConfig(n_paths=2, chunk_size=2))
    ks = np.linspace(-0.3, 0.3, 13)
    for pert in PERTURBATIONS:
        bumped, achieved = engine.perturbed_state(state, _constant(pert), 1.0, label=pert.kind)
        assert achieved == 1.0, pert.kind
        surf = surface_of(bumped)
        assert isinstance(surf, PerturbedSurface) and surf.base.__class__ is ESSVISurface
        for T in (0.25, 1.0, 2.0):
            d = surf.implied_vol_k(ks, T) - base.implied_vol_k(ks, T)
            if pert.kind == "parallel":
                np.testing.assert_allclose(d, 0.01, atol=1e-12)
            elif pert.kind == "shift_k":
                np.testing.assert_allclose(
                    surf.implied_vol_k(ks, T), base.implied_vol_k(ks + 0.01, T), atol=1e-12
                )
            elif pert.kind == "atm_shift":
                np.testing.assert_allclose(d, 0.01 * base.atm_skew(max(T, 1 / 12)), atol=1e-5)
            assert np.all(np.isfinite(d)), pert.kind
    # a bump too large for the checks is halved on the eSSVI base as on the SSVI one
    big, achieved = engine.perturbed_state(state, _skew_tent, 0.8, label="big skew")
    assert achieved == 0.1 and isinstance(surface_of(big), PerturbedSurface)


# --------------------------------------------------------------------------------------------
# the walking test (CONTRIBUTING: the invariant enforced in one place, every site walked)
# --------------------------------------------------------------------------------------------

SURFACE_CLASSES = frozenset({"SSVISurface", "ESSVISurface"})
ALLOWED_CONSTRUCTORS: frozenset[tuple[str, str]] = frozenset(
    {
        ("volsto/market/surface.py", "surface_from_config"),
        # the importer builds its fitted surface from the fit's arrays, not from a config
        ("volsto/market/import_hdn.py", "fit_ssvi"),
    }
)
ALLOWED_CONFIG_READERS: frozenset[tuple[str, str]] = frozenset(
    {("volsto/market/loaders.py", "load_surface_config")}
)


def _name(node: ast.AST) -> str | None:
    if isinstance(node, ast.Name):
        return node.id
    if isinstance(node, ast.Attribute):
        return node.attr
    return None


def _violations(path: Path, rel: str) -> list[str]:
    tree = ast.parse(path.read_text(encoding="utf-8"), filename=rel)
    out: list[str] = []

    def visit(node: ast.AST, func: str) -> None:
        if isinstance(node, ast.FunctionDef | ast.AsyncFunctionDef):
            func = node.name
        if isinstance(node, ast.Call):
            f = node.func
            if (
                isinstance(f, ast.Attribute)
                and f.attr == "from_config"
                and _name(f.value) in SURFACE_CLASSES
            ):
                out.append(f"{rel}:{node.lineno} {_name(f.value)}.from_config (use the factory)")
            if _name(f) in SURFACE_CLASSES and (rel, func) not in ALLOWED_CONSTRUCTORS:
                out.append(f"{rel}:{node.lineno} {_name(f)}(...) in {func}")
            if (
                _name(f) == "load_yaml"
                and any(_name(a) == "SSVIConfig" for a in [*node.args, *(k.value for k in node.keywords)])
                and (rel, func) not in ALLOWED_CONFIG_READERS
            ):  # fmt: skip
                out.append(f"{rel}:{node.lineno} load_yaml(..., SSVIConfig) in {func}")
        if (
            isinstance(node, ast.Subscript)
            and isinstance(node.ctx, ast.Load)
            and isinstance(node.slice, ast.Constant)
            and node.slice.value == "ssvi"
            and (rel, func) not in ALLOWED_CONFIG_READERS
        ):
            out.append(f"{rel}:{node.lineno} raw ['ssvi'] section read in {func}")
        for child in ast.iter_child_nodes(node):
            visit(child, func)

    visit(tree, "<module>")
    return out


def test_every_surface_is_built_by_the_factory() -> None:
    """Walks every module of ``volsto/`` and ``scripts/``: no ``SSVISurface.from_config``, no
    SSVI / eSSVI constructor outside the factory (and the importer's fit), no ``SSVIConfig``
    read from a file and no raw ``["ssvi"]`` section read outside the loader.  A new site
    fails here instead of silently flattening an eSSVI snapshot."""
    files = sorted([*(ROOT / "volsto").rglob("*.py"), *(ROOT / "scripts").rglob("*.py")])
    assert len(files) > 50
    bad = [v for p in files for v in _violations(p, p.relative_to(ROOT).as_posix())]
    assert not bad, "\n".join(bad)
    # the walker sees what it forbids
    probe = ROOT / "tests" / "test_surface_config.py"
    found = _violations(probe, "tests/test_surface_config.py")
    assert any("SSVISurface.from_config" in v for v in found)
    assert any("ESSVISurface(...)" in v for v in found)


# --------------------------------------------------------------------------------------------
# marking points: the stored surface digest (verification follow-up L5)
# --------------------------------------------------------------------------------------------


def test_resume_recomputes_a_marking_point_whose_surface_changed(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, caplog: pytest.LogCaptureFixture
) -> None:
    """A marking point's id names its surface, not the surface's content: the precompute records
    :func:`~volsto.viewers.grid.surface_digest` in the point's manifest and ``--resume``
    (:func:`~volsto.viewers.precompute.pending_steps`) recomputes a stored point whose digest
    differs from the grid surface's (or was never recorded), with a log line; the id format is
    unchanged.  No fit and no calibration: the fit is stubbed infeasible."""
    import logging

    from volsto.calibration.cache import LeverageCache
    from volsto.viewers import precompute
    from volsto.viewers.grid import surface_digest
    from volsto.viewers.store import PointResult, ResultsStore

    grid = load_grid(GRIDS / "default.yaml")
    point = next(
        p for p in enumerate_points(grid) if p.surface == "spx_2022-12-02" and p.mode == "marking"
    )
    assert point.id == "marking:spx_2022-12-02:ssr0.75:eps0.05"
    assert point.spec.surface.rhos is not None
    digest = surface_digest(point.spec)
    assert lv_key(point.spec) == "lv:" + digest
    flat = dataclasses.replace(
        point.spec, surface=dataclasses.replace(point.spec.surface, rhos=None)
    )
    assert surface_digest(flat) != digest

    def infeasible(p: object, surface: object) -> object:
        return dataclasses.replace(point, status="infeasible", resolved=True)

    monkeypatch.setattr(precompute, "resolve_marking", infeasible)
    cache = LeverageCache(tmp_path / "cache")
    res = precompute.compute_point(point, grid, cache, "none")
    assert res.manifest["surface_digest"] == digest
    assert not (tmp_path / "cache").exists()  # nothing calibrated
    store = ResultsStore(tmp_path / "store")
    store.write_point(res)
    assert precompute.pending_steps(point, store, cache, "none") == ()
    for stored in (surface_digest(flat), None):
        manifest = dict(res.manifest)
        if stored is None:
            manifest.pop("surface_digest")
        else:
            manifest["surface_digest"] = stored
        store.write_point(PointResult(res.point_id, res.row, res.tables, manifest))
        caplog.clear()
        with caplog.at_level(logging.INFO, logger="volsto.viewers.precompute"):
            assert precompute.pending_steps(point, store, cache, "none") == ("all",)
        assert any("stale" in r.getMessage() for r in caplog.records)
    # the other modes ignore the digest (their ids carry the content)
    lv_point = next(
        p for p in enumerate_points(grid) if p.surface == "spx_2022-12-02" and p.mode == "lv"
    )
    assert lv_point.id == lv_key(lv_point.spec)
