"""Smile-dynamics analytics (SPEC §4.4, §7.14, §15 Part 1; Bergomi ch. 9 and §12.4).

Every quantity here is a property of the model *with its leverage function held fixed* (book
§12.3.2: the gamma/theta break-even levels of the mixed model are those generated by the model
with a fixed local volatility function), so nothing recalibrates.  For a pure
:class:`~volsto.models.bergomi.BergomiSV` model ``L ≡ 1``.

* :func:`ssr_numerical` — the skew-stickiness ratio at ``t = 0``, book eqs. 9.3 / 12.50,

      ``R_T = (1/S_T) E[dσ̂_T d ln S] / E[(d ln S)²]``,

  by the single-reprice estimator of §12.4.3 (§9.8 for pure SV): with ``L`` fixed the ATMF vol
  is a function ``σ̂_T(ln S, X¹, X²)``, hence

      ``R_T = (1/(S_T σ_0)) [σ_0 ∂σ̂_T/∂ln S + ρ_SX1 ∂σ̂_T/∂X¹ + ρ_SX2 ∂σ̂_T/∂X²]``,
      ``σ_0 = L(0, S_0) sqrt(ξ_0^0)``,

  evaluated with the joint bump ``(ln S_0 + ε σ_0, X_i = ε ρ_SXi)`` of the initial state and the
  ATMF option (strike = forward of the bumped spot) repriced under common random numbers;
  ``S_T`` is the model's own ATMF skew from two strikes around the forward on the same paths.
  ``kind="spot"`` bumps ``ln S_0`` alone (the risk layer's ``"model"`` regime move, M5), and
  ``kind="factors"`` the factors alone (the pure-SV estimator of §9.8).
* :func:`ssr_decomposition` — the order-one decomposition eq. 12.52,

      ``R_T = R_T^LV(Mkt) + (S_T^SV / S_T) [R_T^SV − R_T^LV(SV)]``,

  with ``R^LV`` from eqs. 12.53–12.54 (or their ATMF-term-structure forms, book p. 477),
  ``S^SV`` from eq. 8.55 / 9.18 and ``R^SV`` from eq. 9.21 / 9.19.
* :func:`ssr_short_horizon` — the independent estimator: simulate to ``t``, conditional ATMF
  vol by regression of the ``T``-maturity ATMF payoff on a polynomial basis in ``(ln S_t, X_t)``,
  regression of ``σ̂_T(t)`` on ``ln S_t`` across paths, divided by ``S_T``.
* :func:`atmf_vol_of_vol` — eq. 12.56: the same state-bump partials squared and combined with
  the instantaneous covariance of ``(ln S, X¹, X²)`` give the lognormal vol of the ATMF vol.
* :func:`conditional_smile` — the smile at horizon ``t`` conditional on a spot move.
* :func:`volvol_term_structure` — vol of VS vols: eq. 7.39 for the kernel and, by the same
  state-bump partials applied to the model's VS variance ``E[∫₀ᵀ L² ξ_u^u du]/T``, the
  leverage-included value (reduces to eq. 7.39 exactly for pure SV).

Standard errors are those of the per-path common-random-number differences (linearised implied
vols ``payoff / vega``) propagated by the delta method through ratios and quadratic forms; the
regression estimators use batch means.  Checked by ``tests/test_smile_dynamics.py``.
"""

from __future__ import annotations

import itertools
from collections.abc import Callable, Sequence
from dataclasses import dataclass

import numpy as np
import pandas as pd
from numpy.typing import ArrayLike, NDArray
from scipy.special import ndtri

from volsto.analytics.bergomi import (
    atmf_skew_order1,
    atmf_skew_order1_flat,
    ssr_order1,
    ssr_order1_flat,
    vs_vol_of_vol,
)
from volsto.analytics.mixing import mixing_atmf_skew
from volsto.config import SimConfig
from volsto.engine.grid import TimeGrid
from volsto.engine.mc import MonteCarlo
from volsto.engine.rng import GaussianDraws
from volsto.market.bs import black_vega, implied_vol
from volsto.market.surface import ImpliedSurface, atm_skew_numeric
from volsto.market.varswap import ForwardVarianceCurve
from volsto.models.base import Model
from volsto.models.bergomi import BergomiSV
from volsto.models.localvol import LocalVol
from volsto.models.lsv import LSV
from volsto.products.vanilla import EuropeanOption

FloatArray = NDArray[np.float64]

SSR_KINDS = ("joint", "spot", "factors")
SCHEMES = ("central", "forward")
TERM_STRUCTURES = ("flat", "atmf", "vs")
SKEW_SV_METHODS = ("order1", "mixing")


# --------------------------------------------------------------------------------------------
# model helpers
# --------------------------------------------------------------------------------------------


def kernel_of(model: Model) -> BergomiSV:
    """The Bergomi kernel of a ``BergomiSV`` or ``LSV`` model."""
    if isinstance(model, BergomiSV):
        return model
    if isinstance(model, LSV):
        return model.kernel
    raise TypeError("this analytic needs a BergomiSV or LSV model")


def factor_loadings(model: Model) -> tuple[FloatArray, FloatArray]:
    """``(ρ_S, corr_X)`` of the model's factors: the kernel's ``corr(W^S, W^i)`` and factor
    correlation matrix for a Bergomi-based model, empty arrays for a factor-less model (local
    vol, Black–Scholes), whose smile dynamics is spot-driven only."""
    if isinstance(model, BergomiSV | LSV):
        k = kernel_of(model)
        return k.rho_s, k.corr_x
    if model.n_factors == 0:
        return np.zeros(0), np.zeros((0, 0))
    raise TypeError("smile-dynamics analytics need a BergomiSV, LSV or factor-less model")


def initial_vol(model: Model) -> float:
    """``σ_0 = L(0, S_0) sqrt(ξ_0^0)`` (``L = 1`` for pure SV; the kernel's ``x0`` included)."""
    v0 = model.instantaneous_variance(model.initial_state(2))
    return float(np.sqrt(float(np.mean(v0))))


def state_covariance(model: Model) -> FloatArray:
    """Instantaneous covariance per unit time of ``(ln S, X¹, …, X^nf)`` at ``t = 0`` (book
    §12.4.3): ``E[(d ln S)²] = σ_0² dt``, ``E[d ln S dX^i] = ρ_SXi σ_0 dt``, ``E[dX^i dX^j] =
    ρ_ij dt``."""
    rho_s, corr_x = factor_loadings(model)
    s0 = initial_vol(model)
    nf = rho_s.size
    cov = np.empty((1 + nf, 1 + nf))
    cov[0, 0] = s0 * s0
    cov[0, 1:] = cov[1:, 0] = rho_s * s0
    cov[1:, 1:] = corr_x
    return cov


def state_bump(model: Model, *, d_ln_s: float = 0.0, dx: ArrayLike | None = None) -> Model:
    """The model with its initial state bumped: ``ln S_0 → ln S_0 + d_ln_s`` with the local
    volatility held fixed in spot (the LSV's :meth:`~volsto.models.lsv.LSV.bump` re-anchors
    ``L``; a :class:`~volsto.models.localvol.LocalVol` gets its Dupire surface re-anchored the
    same way — the book's fixed local volatility function; other models through their own
    ``bump(spot=)``) and ``X_0 → X_0 + dx`` for the Bergomi-based models."""
    dx_ = None if dx is None else np.asarray(dx, dtype=np.float64)
    moves_factors = dx_ is not None and bool(np.any(dx_ != 0.0))
    if isinstance(model, LocalVol):
        if moves_factors:
            raise ValueError("a local-vol model has no factor state to bump")
        if d_ln_s == 0.0:
            return model
        fc = model.forward_curve.with_spot(model.spot * float(np.exp(d_ln_s)))
        return LocalVol(model.local_vol.reanchored(fc), fc)
    kwargs: dict[str, object] = {}
    if d_ln_s != 0.0:
        kwargs["spot"] = model.spot * float(np.exp(d_ln_s))
    if moves_factors and dx_ is not None:
        kwargs["x0"] = kernel_of(model).x0 + dx_
    return model.bump(**kwargs) if kwargs else model


def _pairs(x: FloatArray, antithetic: bool) -> FloatArray:
    return 0.5 * (x[0::2] + x[1::2]) if antithetic else x


def _se(samples: FloatArray) -> float:
    n = samples.shape[0]
    return float(samples.std(ddof=1) / np.sqrt(n)) if n > 1 else float("nan")


def _ratio(a: float, b: float, sa: FloatArray, sb: FloatArray) -> tuple[float, float]:
    """``a / b`` with the delta-method standard error from the per-path influence samples
    ``sa``, ``sb`` (means ``a``, ``b``)."""
    infl = (sa - a) / b - a / (b * b) * (sb - b)
    return a / b, _se(infl)


def _check(kind: str, allowed: Sequence[str], name: str) -> None:
    if kind not in allowed:
        raise ValueError(f"{name} must be one of {tuple(allowed)}, got {kind!r}")


# --------------------------------------------------------------------------------------------
# ATMF quotes under common random numbers
# --------------------------------------------------------------------------------------------


@dataclass
class _Quotes:
    """Implied vols of the strikes ``F_T e^k`` for several maturities on one path set, with the
    per-path linearised vol samples ``payoff / vega`` (antithetic pairs averaged)."""

    Ts: FloatArray
    ks: FloatArray
    forward: FloatArray  # (nT,)
    iv: FloatArray  # (nT, nk)
    samples: FloatArray  # (n_samples, nT, nk)


def _atmf_quotes(
    model: Model,
    Ts: FloatArray,
    ks: FloatArray,
    mc: MonteCarlo,
    grid: TimeGrid,
    draws: GaussianDraws,
) -> _Quotes:
    fc = model.forward_curve
    rc = fc.rate_curve
    F = np.asarray(fc.forward(Ts), dtype=np.float64)
    df = np.asarray(rc.df(Ts), dtype=np.float64)
    # calls at every strike: the per-path difference between the ±h strikes is then a call
    # spread bounded by 2hF (out-of-the-money puts below the forward would make it a full payoff)
    products = [
        EuropeanOption(float(F[i] * np.exp(k)), float(T), 1, rc)
        for i, T in enumerate(Ts)
        for k in ks
    ]
    res = mc.price_many(products, model, grid=grid, draws=draws, keep_payoffs=True)
    nT, nk = Ts.size, ks.size
    means = np.array([r.mean for r in res]).reshape(nT, nk)
    pays = np.stack([_pairs(np.asarray(r.payoffs), mc.cfg.antithetic) for r in res], axis=1)
    K = F[:, None] * np.exp(ks)[None, :]
    iv = implied_vol(means, F[:, None], K, Ts[:, None], 1, df[:, None])
    if not np.all(np.isfinite(iv)):
        raise ValueError("implied-vol inversion failed for an ATMF quote")
    vega = black_vega(F[:, None], K, Ts[:, None], iv, df[:, None])
    samples = pays.reshape(pays.shape[0], nT, nk) / vega[None, :, :]
    return _Quotes(Ts, ks, F, np.asarray(iv, dtype=np.float64), samples)


def _skew(q: _Quotes, h: float) -> tuple[FloatArray, FloatArray]:
    """``(S_T, per-path samples)`` from the ``±h`` columns of quotes with ``ks = (−h, 0, h)``."""
    skew = (q.iv[:, 2] - q.iv[:, 0]) / (2.0 * h)
    samples = (q.samples[:, :, 2] - q.samples[:, :, 0]) / (2.0 * h)
    return np.asarray(skew, dtype=np.float64), np.asarray(samples, dtype=np.float64)


def _grid_and_draws(
    model: Model, Ts: FloatArray, sim: SimConfig
) -> tuple[MonteCarlo, TimeGrid, GaussianDraws]:
    mc = MonteCarlo(sim)
    rc = model.forward_curve.rate_curve
    probe = [EuropeanOption(model.spot, float(T), 1, rc) for T in Ts]
    grid = mc.build_grid(probe, model)
    return mc, grid, mc.draws_for(grid, model)


def _bump_scales(model: Model) -> FloatArray:
    """Per state coordinate: ``ln S`` moves by ``ε σ_0``, each factor by ``ε``."""
    rho_s, _ = factor_loadings(model)
    return np.concatenate(([initial_vol(model)], np.ones(rho_s.size)))


# --------------------------------------------------------------------------------------------
# numerical SSR
# --------------------------------------------------------------------------------------------


@dataclass(frozen=True)
class SSRNumerical:
    """Skew-stickiness ratio from the state-bump estimator (book §12.4.3 / §9.8).

    ``numerator = [σ̂_T(+ε) − σ̂_T(−ε)] / (2ε)`` (vol per unit ``ε``), ``slope = numerator / σ_0 =
    E[dσ̂_T d ln S] / E[(d ln S)²]`` (the ATMF-vol shift per unit ``Δ ln S``, SPEC §7.2's
    ``SSR_T · s_T``) and ``R = slope / skew`` with ``skew = S_T`` the model's own ATMF skew.
    """

    T: float
    kind: str
    eps: float
    scheme: str
    R: float
    R_stderr: float
    slope: float
    slope_stderr: float
    numerator: float
    numerator_stderr: float
    skew: float
    skew_stderr: float
    skew_h: float
    sigma_0: float
    atmf_vol: float
    atmf_vol_stderr: float
    n_paths: int

    def __repr__(self) -> str:
        return (
            f"SSRNumerical(T={self.T:g}, {self.kind}: R = {self.R:.4f} ± {self.R_stderr:.4f}, "
            f"slope = {self.slope:.4f} ± {self.slope_stderr:.4f}, S_T = {self.skew:.4f} ± "
            f"{self.skew_stderr:.4f}, sigma_0 = {self.sigma_0:.4f}, eps = {self.eps:g})"
        )


def ssr_numerical_many(
    model: Model,
    Ts: ArrayLike,
    *,
    eps: float,
    sim: SimConfig,
    kind: str = "joint",
    scheme: str = "central",
    skew_h: float = 0.01,
) -> list[SSRNumerical]:
    """:func:`ssr_numerical` for several maturities on one path set (three simulations in all
    for the central scheme, two for the forward one)."""
    _check(kind, SSR_KINDS, "kind")
    _check(scheme, SCHEMES, "scheme")
    if eps <= 0 or skew_h <= 0:
        raise ValueError("eps and skew_h must be positive")
    Ts_ = np.unique(np.atleast_1d(np.asarray(Ts, dtype=np.float64)))
    if np.any(Ts_ <= 0):
        raise ValueError("maturities must be positive")
    rho_s, _ = factor_loadings(model)
    if kind == "factors" and rho_s.size == 0:
        raise ValueError("kind='factors' needs a model with factors")
    s0 = initial_vol(model)
    mc, grid, draws = _grid_and_draws(model, Ts_, sim)
    ks3 = np.array([-skew_h, 0.0, skew_h])
    base = _atmf_quotes(model, Ts_, ks3, mc, grid, draws)
    skew, skew_s = _skew(base, skew_h)

    def bumped(sign: float) -> Model:
        d_ln_s = sign * eps * s0 if kind in ("joint", "spot") else 0.0
        dx = sign * eps * rho_s if kind in ("joint", "factors") else None
        return state_bump(model, d_ln_s=d_ln_s, dx=dx)

    k0 = np.array([0.0])
    up = _atmf_quotes(bumped(+1.0), Ts_, k0, mc, grid, draws)
    if scheme == "central":
        dn = _atmf_quotes(bumped(-1.0), Ts_, k0, mc, grid, draws)
        num = (up.iv[:, 0] - dn.iv[:, 0]) / (2.0 * eps)
        num_s = (up.samples[:, :, 0] - dn.samples[:, :, 0]) / (2.0 * eps)
    else:
        num = (up.iv[:, 0] - base.iv[:, 1]) / eps
        num_s = (up.samples[:, :, 0] - base.samples[:, :, 1]) / eps
    out = []
    for i, T in enumerate(Ts_):
        R, R_se = _ratio(float(num[i]) / s0, float(skew[i]), num_s[:, i] / s0, skew_s[:, i])
        out.append(
            SSRNumerical(
                float(T),
                kind,
                float(eps),
                scheme,
                R,
                R_se,
                float(num[i]) / s0,
                _se(num_s[:, i]) / s0,
                float(num[i]),
                _se(num_s[:, i]),
                float(skew[i]),
                _se(skew_s[:, i]),
                float(skew_h),
                s0,
                float(base.iv[i, 1]),
                _se(base.samples[:, i, 1]),
                int(sim.n_paths),
            )
        )
    return out


def ssr_numerical(
    model: Model,
    T: float,
    *,
    eps: float,
    sim: SimConfig,
    kind: str = "joint",
    scheme: str = "central",
    skew_h: float = 0.01,
) -> SSRNumerical:
    """Numerical SSR at ``t = 0`` (book §12.4.3 for the LSV, §9.8 for pure SV; SPEC §4.4).

    ``kind="joint"``: ``(ln S_0 + ε σ_0, X_i + ε ρ_SXi)`` — the estimator of ``R_T``;
    ``"spot"``: ``ln S_0 + ε σ_0`` alone with the factors at zero (the ``"model"`` delta regime
    of the risk layer, whose ATM-vol shift per unit ``Δ ln S`` is this ``slope``); ``"factors"``:
    the factors alone.  ``scheme="central"`` uses ``±ε`` (three simulations), ``"forward"``
    ``+ε`` against the base.  Checked by ``tests/test_smile_dynamics.py::
    test_ssr_numerical_pure_sv_matches_order_one`` (eq. 9.21 within the order-one accuracy),
    ``test_ssr_numerical_eps_independence`` and, on the cached LSV, the decomposition and M5
    regime tests.
    """
    return ssr_numerical_many(
        model, [T], eps=eps, sim=sim, kind=kind, scheme=scheme, skew_h=skew_h
    )[0]


# --------------------------------------------------------------------------------------------
# volatility of the ATMF volatility (eq. 12.56)
# --------------------------------------------------------------------------------------------


@dataclass(frozen=True)
class ATMFVolOfVol:
    """Instantaneous lognormal vol of the ATMF vol of maturity ``T`` from the state-bump
    partials ``∂σ̂_T/∂(ln S, X¹, X²)`` and the state covariance (book eq. 12.56)."""

    T: float
    eps: float
    scheme: str
    atmf_vol: float
    atmf_vol_stderr: float
    sigma_0: float
    labels: tuple[str, ...]
    partials: FloatArray
    partials_stderr: FloatArray
    covariance: FloatArray
    variance_rate: float
    vol_of_vol: float
    vol_of_vol_stderr: float
    spot_vol_correlation: float
    ssr: float
    ssr_stderr: float
    skew: float
    skew_stderr: float
    vs_vol_of_vol: float
    n_paths: int

    def __repr__(self) -> str:
        parts = ", ".join(
            f"d/d{lab} = {v:.4f} ± {s:.4f}"
            for lab, v, s in zip(self.labels, self.partials, self.partials_stderr)
        )
        return (
            f"ATMFVolOfVol(T={self.T:g}: vol of vol = {self.vol_of_vol:.4f} ± "
            f"{self.vol_of_vol_stderr:.4f} (eq. 7.39 VS: {self.vs_vol_of_vol:.4f}), "
            f"corr(dS, dsigma) = {self.spot_vol_correlation:.3f}, R = {self.ssr:.3f} ± "
            f"{self.ssr_stderr:.3f}; {parts})"
        )


def _partials_from_quotes(
    model: Model,
    Ts: FloatArray,
    eps: float,
    scheme: str,
    mc: MonteCarlo,
    grid: TimeGrid,
    draws: GaussianDraws,
    base: _Quotes,
) -> tuple[FloatArray, FloatArray]:
    """State-bump partials of the ATMF vol: ``(values (nT, 1+nf), samples (n, nT, 1+nf))``."""
    scales = _bump_scales(model)
    nf = scales.size - 1
    k0 = np.array([0.0])
    vals = []
    samps = []
    for j in range(1 + nf):

        def bumped(sign: float, j: int = j) -> Model:
            if j == 0:
                return state_bump(model, d_ln_s=sign * eps * scales[0])
            dx = np.zeros(nf)
            dx[j - 1] = sign * eps
            return state_bump(model, dx=dx)

        up = _atmf_quotes(bumped(+1.0), Ts, k0, mc, grid, draws)
        if scheme == "central":
            dn = _atmf_quotes(bumped(-1.0), Ts, k0, mc, grid, draws)
            dn_v, dn_s = dn.iv[:, 0], dn.samples[:, :, 0]
            denom = 2.0 * eps * scales[j]
        else:
            dn_v, dn_s = base.iv[:, 1], base.samples[:, :, 1]
            denom = eps * scales[j]
        vals.append((up.iv[:, 0] - dn_v) / denom)
        samps.append((up.samples[:, :, 0] - dn_s) / denom)
    return np.stack(vals, axis=1), np.stack(samps, axis=2)


def _quadratic_form(
    p: FloatArray, samples: FloatArray, cov: FloatArray
) -> tuple[float, float, FloatArray]:
    """``p' C p`` with its delta-method standard error from the per-path samples ``(n, m)`` of
    ``p``; also returns the influence samples of the form."""
    g = 2.0 * cov @ p
    infl = (samples - p[None, :]) @ g
    return float(p @ cov @ p), _se(infl), infl


def atmf_vol_of_vol(
    model: Model,
    T: float,
    *,
    eps: float,
    sim: SimConfig,
    scheme: str = "central",
    skew_h: float = 0.01,
) -> ATMFVolOfVol:
    """Volatility of the ATMF volatility of maturity ``T`` (book §12.4.3, eq. 12.56).

    With ``L`` fixed, ``dσ̂_T = ∂σ̂_T/∂ln S d ln S + Σ_i ∂σ̂_T/∂X^i dX^i``; each partial is a
    central (or forward) difference of the ATMF vol under a bump of one state coordinate
    (``ln S_0 ± ε σ_0`` with ``L`` held in spot, ``X^i_0 ± ε``) on common random numbers, and

        ``Var(dσ̂_T)/dt = p' C p``,   ``C`` = :func:`state_covariance`,

    so the lognormal vol of vol is ``sqrt(p' C p) / σ̂_T``; the spot/vol correlation is
    ``(C p)_0 / (σ_0 sqrt(p' C p))`` and the SSR ``(σ_0 p_0 + Σ ρ_SXi p_i) / (σ_0 S_T)`` comes
    from the same partials (a cross-check of :func:`ssr_numerical`).  For pure SV the order-one
    prediction (book eqs. 7.36 / 12.47–12.49) is that ``σ̂_T`` carries the vol of vol of the VS vol
    of the same maturity, eq. 7.39 (``vs_vol_of_vol``, reported alongside); at ``T → 0`` both tend
    to ``ν``.  Checked by ``tests/test_smile_dynamics.py::test_atmf_vol_of_vol_short_maturity``.
    """
    _check(scheme, SCHEMES, "scheme")
    if eps <= 0 or T <= 0 or skew_h <= 0:
        raise ValueError("eps, T and skew_h must be positive")
    rho_s, _ = factor_loadings(model)
    Ts = np.array([float(T)])
    mc, grid, draws = _grid_and_draws(model, Ts, sim)
    base = _atmf_quotes(model, Ts, np.array([-skew_h, 0.0, skew_h]), mc, grid, draws)
    skew, skew_s = _skew(base, skew_h)
    vals, samps = _partials_from_quotes(model, Ts, eps, scheme, mc, grid, draws, base)
    p = vals[0]
    ps = samps[:, 0, :]
    cov = state_covariance(model)
    s0 = float(np.sqrt(cov[0, 0]))
    vr, vr_se, _ = _quadratic_form(p, ps, cov)
    if vr <= 0:
        raise ValueError("non-positive variance rate: the partials are pure noise at this size")
    sig = float(base.iv[0, 1])
    volvol = float(np.sqrt(vr)) / sig
    volvol_se = vr_se / (2.0 * np.sqrt(vr) * sig)
    corr = float(cov[0] @ p) / (s0 * float(np.sqrt(vr)))
    w = np.concatenate(([1.0], rho_s / s0))  # (σ_0 p_0 + Σ ρ_i p_i) / σ_0
    R, R_se = _ratio(float(w @ p), float(skew[0]), ps @ w, skew_s[:, 0])
    labels = ("ln S", *(f"X{i + 1}" for i in range(rho_s.size)))
    vs_ref = _kernel_vs_volvol(model, Ts)[0]
    return ATMFVolOfVol(
        float(T),
        float(eps),
        scheme,
        sig,
        _se(base.samples[:, 0, 1]),
        s0,
        labels,
        p,
        np.array([_se(ps[:, j]) for j in range(ps.shape[1])]),
        cov,
        vr,
        volvol,
        volvol_se,
        corr,
        R,
        R_se,
        float(skew[0]),
        _se(skew_s[:, 0]),
        float(vs_ref),
        int(sim.n_paths),
    )


def _kernel_vs_volvol(model: Model, Ts: FloatArray) -> FloatArray:
    """Eq. 7.39 with the kernel's curve; ``nan`` for a factor-less model."""
    if not isinstance(model, BergomiSV | LSV):
        return np.full(Ts.size, np.nan)
    k = kernel_of(model)
    return np.array([vs_vol_of_vol(k.params, float(T), k.xi0) for T in Ts])


def _kernel_vs_vol(model: Model, Ts: FloatArray) -> FloatArray:
    """``sqrt(W(T)/T)`` of the kernel's curve; ``nan`` for a factor-less model."""
    if not isinstance(model, BergomiSV | LSV):
        return np.full(Ts.size, np.nan)
    k = kernel_of(model)
    return np.sqrt(np.asarray(k.xi0.total_variance(Ts), dtype=np.float64) / Ts)


# --------------------------------------------------------------------------------------------
# order-one decomposition (eq. 12.52)
# --------------------------------------------------------------------------------------------


@dataclass(frozen=True)
class SSRDecomposition:
    """Terms of book eq. 12.52 ``R_T = R^LV(Mkt) + (S^SV_T / S_T) [R^SV_T − R^LV(SV)]``."""

    T: float
    term_structure: str
    skew_sv_method: str
    R: float
    R_lv_market: float
    R_lv_sv: float
    R_sv: float
    skew_market: float
    skew_sv: float
    skew_sv_stderr: float
    skew_ratio: float
    sigma_hat_T: float
    sigma_0: float
    n_quad: int

    @property
    def R_stderr(self) -> float:
        """Propagated from ``S^SV_T`` only (zero for the order-one skew)."""
        return abs(self.R_sv - self.R_lv_sv) / abs(self.skew_market) * self.skew_sv_stderr

    def __repr__(self) -> str:
        return (
            f"SSRDecomposition(T={self.T:g}, {self.term_structure}/{self.skew_sv_method}: "
            f"R = {self.R:.4f} = R_LV(Mkt) {self.R_lv_market:.4f} + {self.skew_ratio:.4f} x "
            f"[R_SV {self.R_sv:.4f} - R_LV(SV) {self.R_lv_sv:.4f}]; S_T = {self.skew_market:.4f}, "
            f"S_SV = {self.skew_sv:.4f} ± {self.skew_sv_stderr:.4f}, sigma_0 = {self.sigma_0:.4f})"
        )


def atmf_variance_curve(surface: ImpliedSurface, t_max: float) -> ForwardVarianceCurve:
    """``σ²(t) = d(σ̂_t² t)/dt`` calibrated to the ATMF term structure of the surface (book
    p. 475: the deterministic volatility of the expansion), as a
    :class:`~volsto.market.varswap.ForwardVarianceCurve` of the ATMF total variances on a
    weekly grid (denser in the first month)."""
    short = np.array([1.0, 2.0, 3.0, 5.0, 10.0, 15.0, 22.0]) / 365.0
    weekly = np.arange(1, int(np.ceil(52 * t_max)) + 2) / 52.0
    mats = np.unique(np.concatenate((short[short < t_max], weekly[weekly < t_max], [t_max])))
    W = np.asarray(surface.atm_vol(mats), dtype=np.float64) ** 2 * mats
    if np.any(np.diff(W) <= 0):
        raise ValueError("the ATMF total variance of the surface is not increasing in T")
    return ForwardVarianceCurve(mats, W)


def _market_skew(surface: ImpliedSurface, t: FloatArray) -> FloatArray:
    fn = getattr(surface, "atm_skew", None)
    if callable(fn):
        return np.asarray(fn(t), dtype=np.float64)
    return atm_skew_numeric(surface, t)


def ssr_decomposition(
    model: Model,
    surface: ImpliedSurface,
    T: float,
    *,
    term_structure: str = "atmf",
    skew_sv_method: str = "order1",
    n_quad: int = 64,
    mixing_paths: int = 100_000,
    mixing_seed: int = 0,
    mixing_dt: float = 1.0 / 365.0,
) -> SSRDecomposition:
    """Book eq. 12.52 for an LSV calibrated to ``surface`` (its kernel supplies the SV terms).

    ``term_structure``: ``"flat"`` — the expansion around the constant ``σ_0 = σ̂_T`` (the ATMF
    vol of maturity ``T``): ``R^LV(Mkt) = 1 + (1/T) ∫₀ᵀ S_t/S_T dt`` (12.53), ``R^LV(SV) = 1 +
    (1/T) ∫₀ᵀ S^SV_t/S^SV_T dt`` (12.54) with ``S^SV`` from eq. 8.55 and ``R^SV`` from eq. 9.21;
    ``"atmf"`` — the book's choice for smiles with a marked term structure (p. 475, 477):
    ``σ²(t) = d(σ̂_t² t)/dt`` from the surface's ATMF vols, ``R^LV = 1 + (1/T) ∫₀ᵀ σ²(t)/(σ̂_t
    σ̂_T) S_t/S_T dt`` and its ``S^SV`` analogue, ``S^SV`` from eq. 9.18 and ``R^SV`` from eq.
    9.19 with ``ξ_0^t = σ²(t)``; ``"vs"`` — the same with the kernel's own forward-variance curve
    (VS vols).  The market skew ``S_t`` is the surface's analytic ATM skew when it has one,
    else a central difference; the ``1/√t`` short end is integrated with ``t = T u²``.
    ``skew_sv_method="mixing"`` replaces ``S^SV_T`` in the prefactor ``S^SV_T/S_T`` by the naked
    kernel's mixing-solution skew (book p. 478: computing ``S^SV_T`` numerically makes the
    decomposition exact when the smile is the kernel's own); the shape ``S^SV_t/S^SV_T`` inside
    ``R^LV(SV)`` stays at order one.  The book's sanity checks hold by construction:
    ``S_T = S^SV_T`` gives ``R = R^SV``, ``ν = 0`` gives ``R = R^LV(Mkt)``.  Measured on the cached
    1F ω = 3 reference LSV (8·10⁵ particles) against :func:`ssr_numerical` in
    ``tests/test_smile_dynamics.py::test_lsv_ssr_decomposition_vs_numerical`` (numbers in the
    test docstring).
    """
    _check(term_structure, TERM_STRUCTURES, "term_structure")
    _check(skew_sv_method, SKEW_SV_METHODS, "skew_sv_method")
    if T <= 0 or n_quad < 4:
        raise ValueError("T must be positive and n_quad >= 4")
    kernel = kernel_of(model)
    p = kernel.params
    u, wu = np.polynomial.legendre.leggauss(n_quad)
    u = 0.5 * (u + 1.0)
    wu = 0.5 * wu
    t = T * u * u  # t = T u²: dt = 2 T u du, so (1/T) ∫ f dt = Σ 2 u w f(t)
    weight = 2.0 * u * wu
    sig_T = float(surface.atm_vol(T))
    S_mkt_t = _market_skew(surface, t)
    S_mkt_T = float(_market_skew(surface, np.array([T]))[0])
    if term_structure == "flat":
        factor = np.ones_like(t)
        S_sv_t = np.asarray(atmf_skew_order1_flat(p, t), dtype=np.float64)
        S_sv_T = float(atmf_skew_order1_flat(p, T))
        R_sv = float(ssr_order1_flat(p, T))
        sigma_0 = sig_T
    else:
        curve = (
            atmf_variance_curve(surface, max(T, 1.5 / 12.0))
            if term_structure == "atmf"
            else kernel.xi0
        )
        sig_t = np.sqrt(np.asarray(curve.total_variance(t), dtype=np.float64) / t)
        sig_T_curve = float(np.sqrt(float(curve.total_variance(T)) / T))
        factor = np.asarray(curve.xi0(t), dtype=np.float64) / (sig_t * sig_T_curve)
        S_sv_t = np.array([atmf_skew_order1(p, curve, float(ti)) for ti in t])
        S_sv_T = float(atmf_skew_order1(p, curve, T))
        R_sv = float(ssr_order1(p, curve, T))
        sigma_0 = float(np.sqrt(float(curve.xi0(0.0))))
    R_lv_mkt = 1.0 + float(np.sum(weight * factor * S_mkt_t / S_mkt_T))
    R_lv_sv = 1.0 + float(np.sum(weight * factor * S_sv_t / S_sv_T))
    S_sv_se = 0.0
    if skew_sv_method == "mixing":
        S_sv_T, _, S_sv_se = mixing_atmf_skew(
            kernel, T, n_paths=mixing_paths, seed=mixing_seed, dt=mixing_dt
        )
    ratio = S_sv_T / S_mkt_T
    R = R_lv_mkt + ratio * (R_sv - R_lv_sv)
    return SSRDecomposition(
        float(T),
        term_structure,
        skew_sv_method,
        R,
        R_lv_mkt,
        R_lv_sv,
        R_sv,
        S_mkt_T,
        S_sv_T,
        S_sv_se,
        ratio,
        sig_T,
        sigma_0,
        int(n_quad),
    )


# --------------------------------------------------------------------------------------------
# regression machinery at a horizon t
# --------------------------------------------------------------------------------------------


def _basis(features: FloatArray, degree: int) -> FloatArray:
    """``[1, x_j, x_j x_k, …]`` up to ``degree`` (with repetition) on standardised features
    (the basis of :func:`volsto.risk.estimators.conditional_greeks`)."""
    n, d = features.shape
    cols = [np.ones(n)]
    for deg in range(1, degree + 1):
        for combo in itertools.combinations_with_replacement(range(d), deg):
            cols.append(np.prod(features[:, list(combo)], axis=1))
    return np.column_stack(cols)


@dataclass
class _Horizon:
    """State at ``t`` and log-spot at ``T`` for every path."""

    t: float
    T: float
    ln_s_t: FloatArray
    factors_t: FloatArray
    ln_s_T: FloatArray
    ln_f_t: float
    ln_f_T: float
    df_T: float


def _simulate_horizon(model: Model, t: float, T: float, sim: SimConfig) -> _Horizon:
    if not 0.0 < t < T:
        raise ValueError("need 0 < t < T")
    grid = TimeGrid.build([t, T], sim.dt_max, calibration_grid=model.required_times())
    idx = grid.fixing_index
    ct, cT = idx[t], idx[T]
    draws = GaussianDraws(sim.seed, sim.n_paths, grid.n_steps, model.n_brownians, sim.antithetic)
    n = sim.n_paths
    ln_s_t = np.empty(n)
    ln_s_T = np.empty(n)
    fac = np.empty((n, model.n_factors))
    for p0, p1 in sim.chunk_ranges(grid.n_records, model.n_factors):
        paths = model.simulate_chunk(grid, draws, p0, p1, sim.scheme)
        ln_s_t[p0:p1] = paths.log_spot_at(ct)
        ln_s_T[p0:p1] = paths.log_spot_at(cT)
        fac[p0:p1] = paths.factors_at(ct)
    fc = model.forward_curve
    return _Horizon(
        t,
        T,
        ln_s_t,
        fac,
        ln_s_T,
        float(fc.log_forward(t)),
        float(fc.log_forward(T)),
        float(fc.rate_curve.df(T)),
    )


def _fit(x: FloatArray, y: FloatArray) -> tuple[FloatArray, float]:
    beta, *_ = np.linalg.lstsq(x, y, rcond=None)
    resid = y - x @ beta
    var_y = float(y.var())
    r2 = 1.0 - float(resid.var()) / var_y if var_y > 0 else 1.0
    return np.asarray(beta, dtype=np.float64), r2


def _batches(n: int, n_batches: int, antithetic: bool) -> list[slice]:
    unit = 2 if antithetic else 1
    size = (n // (n_batches * unit)) * unit
    if size < max(unit, 8):
        raise ValueError("too few paths for the requested number of batches")
    return [slice(b * size, (b + 1) * size) for b in range(n_batches)]


def _batch_stat(
    fn: Callable[[slice], FloatArray], n: int, n_batches: int, antithetic: bool
) -> tuple[FloatArray, FloatArray]:
    """Full-sample value of ``fn`` (vector statistic) with batch-means standard errors."""
    full = np.atleast_1d(fn(slice(0, n)))
    vals = np.stack([np.atleast_1d(fn(s)) for s in _batches(n, n_batches, antithetic)])
    return full, np.asarray(vals.std(axis=0, ddof=1) / np.sqrt(n_batches), dtype=np.float64)


def _atmf_vol_from_normalised_price(price: FloatArray, m: float, tau: float) -> FloatArray:
    """ATMF Black inversion of the undiscounted normalised call ``E[(S_T/S_t − m)⁺ | ·]`` with
    forward = strike = ``m``: ``price = m [2 N(σ√τ/2) − 1]``."""
    x = np.clip(price / m, 1e-12, 1.0 - 1e-12)
    return np.asarray(2.0 / np.sqrt(tau) * ndtri(0.5 * (x + 1.0)), dtype=np.float64)


# --------------------------------------------------------------------------------------------
# short-horizon SSR estimator (slow)
# --------------------------------------------------------------------------------------------


@dataclass(frozen=True)
class SSRShortHorizon:
    """SSR from the regression of the conditional ATMF vol at ``t`` on ``ln S_t`` across paths."""

    T: float
    t: float
    degree: int
    n_batches: int
    R: float
    R_stderr: float
    slope: float
    slope_stderr: float
    skew: float
    skew_stderr: float
    atmf_vol_0: float
    mean_conditional_vol: float
    r2: float
    n_paths: int

    def __repr__(self) -> str:
        return (
            f"SSRShortHorizon(T={self.T:g}, t={self.t:.4g}: R = {self.R:.4f} ± "
            f"{self.R_stderr:.4f}, slope = {self.slope:.4f} ± {self.slope_stderr:.4f}, "
            f"S_T = {self.skew:.4f} ± {self.skew_stderr:.4f}, r2 = {self.r2:.4f})"
        )


def ssr_short_horizon(
    model: Model,
    T: float,
    *,
    sim: SimConfig,
    t: float = 1.0 / 52.0,
    degree: int = 3,
    n_batches: int = 10,
    skew_h: float = 0.01,
) -> SSRShortHorizon:
    """The independent short-horizon estimator of the SSR (SPEC §4.4, book eq. 9.3 read over
    ``[0, t]``): simulate to ``t``; the ATMF-at-``t`` call of maturity ``T`` has strike ``S_t
    F(T)/F(t)`` and its normalised payoff ``(S_T/S_t − m)⁺`` is regressed on the polynomial
    basis in ``(ln S_t, X_t)`` (as :func:`volsto.risk.estimators.conditional_greeks`); the fitted
    conditional price inverts to ``σ̂_T(t)`` (Black, forward = strike); ``slope`` is the
    regression coefficient of ``σ̂_T(t)`` on ``ln S_t`` across paths and ``R = slope / S_T`` with
    ``S_T`` the ``t = 0`` ATMF skew on the same paths.  Standard errors: batch means over
    ``n_batches`` pair-aligned batches for the slope, per-path for the skew, combined in
    quadrature.  Slow: ``tests/test_smile_dynamics.py::test_ssr_short_horizon_slow``.
    """
    if degree < 1 or n_batches < 2 or skew_h <= 0:
        raise ValueError("need degree >= 1, n_batches >= 2, skew_h > 0")
    hz = _simulate_horizon(model, t, T, sim)
    tau = T - t
    m = float(np.exp(hz.ln_f_T - hz.ln_f_t))
    y = np.maximum(np.exp(hz.ln_s_T - hz.ln_s_t) - m, 0.0)
    raw = np.column_stack([hz.ln_s_t, hz.factors_t])
    mean = raw.mean(axis=0)
    scale = np.where(raw.std(axis=0) > 0, raw.std(axis=0), 1.0)
    x = _basis((raw - mean) / scale, degree)
    n = sim.n_paths
    r2_full = 0.0
    mean_vol = 0.0

    def stat(s: slice) -> FloatArray:
        nonlocal r2_full, mean_vol
        beta, r2 = _fit(x[s], y[s])
        sig = _atmf_vol_from_normalised_price(x[s] @ beta, m, tau)
        ls = hz.ln_s_t[s]
        slope = float(np.cov(sig, ls)[0, 1] / ls.var(ddof=1))
        if s.start == 0 and s.stop == n:
            r2_full, mean_vol = r2, float(sig.mean())
        return np.array([slope])

    slope, slope_se = _batch_stat(stat, n, n_batches, sim.antithetic)
    # t = 0 ATMF skew and vol of maturity T on the same paths
    F_T = float(np.exp(hz.ln_f_T))
    ks = np.array([-skew_h, 0.0, skew_h])
    K = F_T * np.exp(ks)
    cps = np.array([-1, 1, 1])
    pays = np.stack(
        [np.maximum(c * (np.exp(hz.ln_s_T) - k), 0.0) * hz.df_T for k, c in zip(K, cps)], axis=1
    )
    iv = implied_vol(pays.mean(axis=0), F_T, K, T, cps, hz.df_T)
    vega = black_vega(F_T, K, T, iv, hz.df_T)
    samp = _pairs(pays, sim.antithetic) / vega[None, :]
    skew = float((iv[2] - iv[0]) / (2.0 * skew_h))
    skew_se = _se((samp[:, 2] - samp[:, 0]) / (2.0 * skew_h))
    R = float(slope[0]) / skew
    R_se = abs(R) * float(np.hypot(slope_se[0] / slope[0], skew_se / skew))
    return SSRShortHorizon(
        float(T),
        float(t),
        int(degree),
        int(n_batches),
        R,
        R_se,
        float(slope[0]),
        float(slope_se[0]),
        skew,
        skew_se,
        float(iv[1]),
        mean_vol,
        r2_full,
        int(n),
    )


# --------------------------------------------------------------------------------------------
# conditional smile after a spot move
# --------------------------------------------------------------------------------------------


@dataclass(frozen=True)
class ConditionalSmile:
    """Implied vols at horizon ``t`` conditional on ``ln S_t − ln F_t = spot_move``, strikes
    ``K = S_t F(T)/F(t) e^k`` (moneyness relative to the conditional forward)."""

    t: float
    T: float
    spot_move: float
    degree: int
    n_batches: int
    ks: FloatArray
    implied_vols: FloatArray
    stderr: FloatArray
    forward_ratio: float
    ln_spot: float
    x_conditional: FloatArray
    r2: FloatArray
    n_paths: int

    @property
    def atmf_vol(self) -> tuple[float, float]:
        """``(σ̂, stderr)`` at ``k = 0`` (raises if ``0`` is not among the strikes)."""
        i = int(np.flatnonzero(np.abs(self.ks) < 1e-12)[0])
        return float(self.implied_vols[i]), float(self.stderr[i])

    def to_dataframe(self) -> pd.DataFrame:
        return pd.DataFrame(
            {"k": self.ks, "implied_vol": self.implied_vols, "stderr": self.stderr, "r2": self.r2}
        )

    def __repr__(self) -> str:
        rows = [
            f"  k={k:+.4f}: iv={iv:.5f} ± {se:.5f}"
            for k, iv, se in zip(self.ks, self.implied_vols, self.stderr)
        ]
        head = (
            f"ConditionalSmile(t={self.t:.4g}, T={self.T:g}, spot_move={self.spot_move:+.4f}, "
            f"E[X|move]={np.round(self.x_conditional, 4).tolist()},\n"
        )
        return head + "\n".join(rows) + "\n)"


def conditional_smile(
    model: Model,
    t: float,
    spot_move: float,
    T: float,
    ks: ArrayLike,
    *,
    sim: SimConfig,
    degree: int = 3,
    n_batches: int = 10,
) -> ConditionalSmile:
    """Smile of maturity ``T`` seen at ``t`` conditional on the spot move ``ln S_t − ln F_t =
    spot_move`` (SPEC §15 Part 1).  The normalised payoffs ``cp_k (S_T/S_t − m e^k)⁺``, ``m =
    F(T)/F(t)`` (out-of-the-money: puts for ``k < 0``), are regressed on the polynomial basis in
    ``(ln S_t, X_t)`` (degree ``degree``, cross terms); the factors are regressed on ``ln S_t``
    alone (same degree) to give ``E[X_t | ln S_t]``; the fitted price at ``(ln F_t + spot_move,
    E[X_t | ·])`` inverts to the Black implied vol with forward ``m``, strike ``m e^k`` and
    maturity ``T − t``.  Standard errors by batch means.  Checked by
    ``tests/test_smile_dynamics.py::test_conditional_smile_first_order_move``: under pure SV the
    ATMF conditional vol moves by ``R_T S_T · spot_move`` to first order.
    """
    if degree < 1 or n_batches < 2:
        raise ValueError("need degree >= 1 and n_batches >= 2")
    ks_ = np.atleast_1d(np.asarray(ks, dtype=np.float64))
    hz = _simulate_horizon(model, t, T, sim)
    tau = T - t
    m = float(np.exp(hz.ln_f_T - hz.ln_f_t))
    cps = np.where(ks_ < 0, -1.0, 1.0)
    ret = np.exp(hz.ln_s_T - hz.ln_s_t)
    y = np.maximum(cps[None, :] * (ret[:, None] - m * np.exp(ks_)[None, :]), 0.0)
    raw = np.column_stack([hz.ln_s_t, hz.factors_t])
    mean = raw.mean(axis=0)
    scale = np.where(raw.std(axis=0) > 0, raw.std(axis=0), 1.0)
    x = _basis((raw - mean) / scale, degree)
    xs = _basis(((hz.ln_s_t - mean[0]) / scale[0])[:, None], degree)  # factors on ln S_t alone
    ln_star = hz.ln_f_t + spot_move
    n = sim.n_paths
    nf = model.n_factors
    r2 = np.zeros(ks_.size)
    x_star = np.zeros(nf)

    def stat(s: slice) -> FloatArray:
        nonlocal r2, x_star
        xst = np.zeros(nf)
        z_star = np.array([(ln_star - mean[0]) / scale[0]])
        for i in range(nf):
            b, _ = _fit(xs[s], hz.factors_t[s, i])
            xst[i] = float((_basis(z_star[:, None], degree) @ b)[0])
        feat = np.concatenate(([ln_star], xst))
        row = _basis(((feat - mean) / scale)[None, :], degree)
        prices = np.empty(ks_.size)
        r2_here = np.empty(ks_.size)
        for j in range(ks_.size):
            b, r2_here[j] = _fit(x[s], y[s, j])
            prices[j] = float((row @ b)[0])
        if s.start == 0 and s.stop == n:
            r2, x_star = r2_here, xst
        return np.asarray(implied_vol(prices, m, m * np.exp(ks_), tau, cps, 1.0), dtype=np.float64)

    iv, se = _batch_stat(stat, n, n_batches, sim.antithetic)
    return ConditionalSmile(
        float(t),
        float(T),
        float(spot_move),
        int(degree),
        int(n_batches),
        ks_,
        iv,
        se,
        m,
        float(ln_star),
        x_star,
        r2,
        int(n),
    )


# --------------------------------------------------------------------------------------------
# vol-of-vol term structure
# --------------------------------------------------------------------------------------------


@dataclass(frozen=True)
class VolVolTermStructure:
    """Instantaneous lognormal vol of the VS vol per maturity: eq. 7.39 for the kernel and the
    leverage-included model value by state-bump partials (see :func:`volvol_term_structure`)."""

    Ts: FloatArray
    eps: float
    scheme: str
    labels: tuple[str, ...]
    kernel_volvol: FloatArray
    model_volvol: FloatArray
    model_volvol_stderr: FloatArray
    vs_vol: FloatArray
    vs_vol_kernel: FloatArray
    partials: FloatArray
    partials_stderr: FloatArray
    covariance: FloatArray
    spot_vol_correlation: FloatArray
    n_paths: int

    def to_dataframe(self) -> pd.DataFrame:
        df = pd.DataFrame(
            {
                "T": self.Ts,
                "volvol_kernel_eq_7_39": self.kernel_volvol,
                "volvol_model": self.model_volvol,
                "volvol_model_stderr": self.model_volvol_stderr,
                "vs_vol_model": self.vs_vol,
                "vs_vol_kernel": self.vs_vol_kernel,
                "spot_vol_corr": self.spot_vol_correlation,
            }
        )
        for j, lab in enumerate(self.labels):
            df[f"dlnvol_d{lab.replace(' ', '')}"] = self.partials[:, j]
        return df

    def __repr__(self) -> str:
        return "VolVolTermStructure(\n" + self.to_dataframe().to_string(index=False) + "\n)"


def volvol_term_structure(
    model: Model,
    Ts: ArrayLike,
    *,
    eps: float,
    sim: SimConfig,
    scheme: str = "central",
) -> VolVolTermStructure:
    """Term structure of the volatility of VS volatilities (SPEC §15 Part 1 item 6).

    Kernel: eq. 7.39 with the kernel's forward-variance curve (``vs_vol_of_vol``).  Model with
    leverage — the definition implemented: the VS variance of maturity ``T`` at ``t = 0`` is
    ``σ̂_T² = E[∫₀ᵀ L²(u, S_u) ξ_u^u du] / T``; with ``L`` fixed it is a function of the initial
    state ``(ln S_0, X_0)`` and its instantaneous lognormal vol is ``sqrt(p' C p)`` with ``p_j =
    ∂ ln σ̂_T / ∂(ln S, X^i)`` by central (or forward) differences of ``ln E[∫ L² ξ]`` under the
    state bumps ``ln S_0 ± ε σ_0`` (``L`` held in spot) and ``X^i_0 ± ε``, on common random
    numbers, and ``C`` the state covariance (as eq. 12.56 for the ATMF vol).  For pure SV
    ``∂ ln σ̂_T/∂X^i = ν α_θ w_i A_i`` exactly (eq. 7.38) and the ``ln S`` partial vanishes, so the
    estimator reduces to eq. 7.39 up to the time discretisation of ``∫ ξ`` and ``O(ε²)``; checked
    within 2 stderr by ``tests/test_smile_dynamics.py::test_volvol_term_structure_pure_sv``.
    The integrated variance is the kernel's accumulator (trapezoid in the SV variance, the
    Platen mid-value with leverage), so this is the model's own variance-swap strip.
    """
    _check(scheme, SCHEMES, "scheme")
    if eps <= 0:
        raise ValueError("eps must be positive")
    Ts_ = np.unique(np.atleast_1d(np.asarray(Ts, dtype=np.float64)))
    if np.any(Ts_ <= 0):
        raise ValueError("maturities must be positive")
    grid = TimeGrid.build(Ts_, sim.dt_max, calibration_grid=model.required_times())
    cols = grid.fixing_index.indices(Ts_)
    draws = GaussianDraws(sim.seed, sim.n_paths, grid.n_steps, model.n_brownians, sim.antithetic)

    def integrated(m: Model) -> FloatArray:
        out = np.empty((sim.n_paths, Ts_.size))
        for p0, p1 in sim.chunk_ranges(grid.n_records, m.n_factors):
            paths = m.simulate_chunk(grid, draws, p0, p1, sim.scheme)
            out[p0:p1] = paths.int_var[:, cols]
        return _pairs(out, sim.antithetic)

    v0 = integrated(model)
    mean0 = v0.mean(axis=0)
    scales = _bump_scales(model)
    nf = scales.size - 1
    vals = []
    samps = []
    for j in range(1 + nf):

        def bumped(sign: float, j: int = j) -> Model:
            if j == 0:
                return state_bump(model, d_ln_s=sign * eps * scales[0])
            dx = np.zeros(nf)
            dx[j - 1] = sign * eps
            return state_bump(model, dx=dx)

        vp = integrated(bumped(+1.0))
        if scheme == "central":
            vm = integrated(bumped(-1.0))
            denom = 2.0 * eps * scales[j]
        else:
            vm = v0
            denom = eps * scales[j]
        # d ln σ̂_T = ½ d ln E[V]; linearised per-path samples (V⁺ − V⁻) / E[V]
        vals.append(0.5 * (np.log(vp.mean(axis=0)) - np.log(vm.mean(axis=0))) / denom)
        samps.append(0.5 * (vp - vm) / mean0[None, :] / denom)
    partials = np.stack(vals, axis=1)  # (nT, 1+nf)
    samples = np.stack(samps, axis=2)  # (n, nT, 1+nf)
    cov = state_covariance(model)
    s0 = float(np.sqrt(cov[0, 0]))
    volvol = np.empty(Ts_.size)
    volvol_se = np.empty(Ts_.size)
    corr = np.empty(Ts_.size)
    for i in range(Ts_.size):
        vr, vr_se, _ = _quadratic_form(partials[i], samples[:, i, :], cov)
        volvol[i] = np.sqrt(max(vr, 0.0))
        volvol_se[i] = vr_se / (2.0 * volvol[i]) if volvol[i] > 0 else float("nan")
        corr[i] = float(cov[0] @ partials[i]) / (s0 * volvol[i]) if volvol[i] > 0 else float("nan")
    labels = ("ln S", *(f"X{i + 1}" for i in range(nf)))
    return VolVolTermStructure(
        Ts_,
        float(eps),
        scheme,
        labels,
        _kernel_vs_volvol(model, Ts_),
        volvol,
        volvol_se,
        np.sqrt(mean0 / Ts_),
        _kernel_vs_vol(model, Ts_),
        partials,
        np.array(
            [[_se(samples[:, i, j]) for j in range(1 + nf)] for i in range(Ts_.size)],
            dtype=np.float64,
        ),
        cov,
        corr,
        int(sim.n_paths),
    )


__all__ = [
    "SCHEMES",
    "SKEW_SV_METHODS",
    "SSR_KINDS",
    "TERM_STRUCTURES",
    "ATMFVolOfVol",
    "ConditionalSmile",
    "SSRDecomposition",
    "SSRNumerical",
    "SSRShortHorizon",
    "VolVolTermStructure",
    "atmf_variance_curve",
    "atmf_vol_of_vol",
    "conditional_smile",
    "initial_vol",
    "kernel_of",
    "ssr_decomposition",
    "ssr_numerical",
    "ssr_numerical_many",
    "ssr_short_horizon",
    "state_bump",
    "state_covariance",
    "volvol_term_structure",
]
